### ISSUE TITLE
Sudoers file

### ISSUE THREAD

**Issue by Yentel** [dg9vh/YSFReflector-Dashboard#1]
**Required are** : entry in /etc/sudoers: www-data ALL=(ALL) NOPASSWD: ALL

With all due respect OM, but have you gone out of your mind? :-1: 
If one tiny bit of your (or any other application) is vulnerable for command execution, your whole pi can be torn to pieces. Please look for other workarounds to fix this.

Best 73'
Yentel - ON3YH

**Comment by Giorgiofox** [comment]
I agree! is really dangerous do that...

**Comment by zarya** [comment]
I reviewed the code but did not find any references to sudo being used.

**Comment by dg9vh** [comment]
Sorry - that happend by copy and paste from another Readme... modified this with https://github.com/dg9vh/YSFReflector-Dashboard/commit/a16271f3ea29811e3cf65226795de141d8055f86 just now... 

Has to check the origin-Readme if this is still necessary there...
