### ISSUE TITLE
Dashboard issues

### ISSUE THREAD

**Issue by sixfootseven** [dg9vh/YSFReflector-Dashboard#10]
My dashboard data goes blank each day at midday.

My server (Ubuntu) is set to correct timezone, and system time is correct.
YSF Reflector logs dont get renewed to the new date (e.g. on the 25th, still using log file for the 24th), until 12pm, then the dashboard stops displaying due to no data.

All the YSF log entries are 12 hours behind.

In my YSF config file I have my timezone set correctly.

After midday each day, restarting the reflector creates a new log file (again, with everything 12 hours behind).

Any ideas?

**Comment by dg9vh** [comment]
It seems that you have not set the write-permissions on your log-directory for the mmdvm-user. Please check, if the YSFReflector is able to write new logfiles after logrotation at 0 UTC.

**Comment by dg9vh** [comment]
Is this issue persisting? If so, reopen it with further information.
