### ISSUE TITLE
YSFReflector online but cannot communicate

### ISSUE THREAD

**Issue by VE2TIH** [dg9vh/YSFReflector-Dashboard#15]
Hi DG9VG, here's VE2TIH from Canada.
Our CA NANIKANA Reflector is finally online (I had a NAT issue previously).
Now it's directly on a public IP 24.212.48.121, no router, no firewall
I have a MMDVM (Pi-Star) that works fine on CA Canada FR, I frequently discuss with dudes via my FTM-3200DR
When I connects on CA NANIKANA with the Pi-Star, I can't talk to anybody, and the dashboard is empty...
My friend uses a DV4 and he can use the YSFReflector. The Shark RF works fine too.
Any idea ?

**Comment by VE2TIH** [comment]
We just found out that the room ID is 19952 but on the Pi-Star it's 14559... That's weird...

**Comment by VE2TIH** [comment]
Room ID corrected, same issue. High BER though. Trying to correct with RX offset...

**Comment by dg9vh** [comment]
It seems that your Reflector is not writing logs or you configured wrong log-location in Dashboard.

High BER is no issue of the Dashboard.

**Comment by VE2TIH** [comment]
If I remember, if left logging OFF because of an error message...
I just corrected that:
[Log]
# Logging levels, 0=No logging
DisplayLevel=1
FileLevel=1
FilePath=/root/YSFClients/YSFReflector
FileRoot=mylog

but...

root@raspberrypi:~/YSFClients/YSFReflector# ./YSFReflector YSFReflector.ini
root@raspberrypi:~/YSFClients/YSFReflector# YSFReflector: unable to open the log file

**Comment by VE2TIH** [comment]
and now YSFReflector refuses to start
root@raspberrypi:~/YSFClients/YSFReflector# ps -aux |grep YSF
root      8892  0.0  0.0   4376   572 pts/0    S+   09:26   0:00 grep YSF

**Comment by VE2TIH** [comment]
When we first registered our DMR ID, we asked for a non-repeater ID (3020424)
This is what we registered CA NANIKANA with.
Does the YSFReflector need to have a DMR ID for a repeater ?
The idea here is to create only a YSFReflector for our operations...

**Comment by dg9vh** [comment]
Please check write-permissions for user mmdvm for the log-directory.

and no, you do not need to register a DmR-ID for the reflector. If you want to get it linked to a BrandMeister-Talkgroup please contact your local BrandMeister-Team to do this.

**Comment by VE2TIH** [comment]
logs seems to be created in the same directory as the program itself
ie:
/root/YSFClients/YSFReflector
There's 2 files already there named 
387015  24 -rw-r--r-- 1 root root  17142 Sep 15 19:58 mylog-2018-09-15.log
387033  44 -rw-r--r-- 1 root root  39034 Sep 16 19:28 mylog-2018-09-16.log
is it a good idea to have all this under root or it would be better to have it under /home/mmdvm ?

**Comment by dg9vh** [comment]
This is, what you gave in the YSFReflector.ini - please correct FilePath=/var/log/YSFReflector and make this directory writeable for user mmdvm.

**Comment by VE2TIH** [comment]
I tried to add write privileges for mmdvm for /var/log directory but I failed all the times... could you please tell me how ?
Thanks

**Comment by dg9vh** [comment]
just do following:
sudo mkdir /var/log/YSFReflector
sudo chown mmdvm /var/log/YSFReflector

now the directory to which the YSFReflector would write it's logs is writeable for mmdvm because this user is the owner of the directory.

**Comment by VE2TIH** [comment]
hahhh ! Thanks !
works now !
73

Michel

------ Original Message ------
