### ISSUE TITLE
Dashboard throws an error 500

### ISSUE THREAD

**Issue by vk7hse** [dg9vh/YSFReflector-Dashboard#16]
I was just updating my YSF reflector dashboard, and on reloading the page it wouldn't load! so went digging and in the apache2 error log was the following...

`pi@raspi-10:/var/log/apache2 $ cat error.log
[Tue Sep 18 11:31:37.021746 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Notice:  Undefined variable: data_path in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.022118 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Warning:  filectime(): stat failed for YSFReflector-2018-09-18.log in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.022266 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Notice:  Undefined variable: data_path in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.022416 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Warning:  filectime(): stat failed for xastir_udp_client in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.022535 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Notice:  Undefined variable: data_path in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.022684 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Warning:  filectime(): stat failed for YSFReflector in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.022794 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Notice:  Undefined variable: data_path in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.022924 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Warning:  filectime(): stat failed for NXDNReflector in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.023031 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Notice:  Undefined variable: data_path in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.023163 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Warning:  filectime(): stat failed for op.sh in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.023270 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Notice:  Undefined variable: data_path in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.023394 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Warning:  filectime(): stat failed for xastir in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.023495 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Notice:  Undefined variable: data_path in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.023613 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Warning:  filectime(): stat failed for callpass in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.023727 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Notice:  Undefined variable: data_path in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.023844 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Warning:  filectime(): stat failed for testdbfawk in /var/www/html/include/functions.php on line 76
[Tue Sep 18 11:31:37.267943 2018] [:error] [pid 820] [client 192.168.178.206:61519] PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (tarting YSFReflecto) at position 0 (t): The timezone could not be found in the database in /var/www/html/include/functions.php:188\nStack trace:\n#0 /var/www/html/include/functions.php(188): DateTime->__construct('tarting YSFRefl...')\n#1 /var/www/html/include/init.php(20): getHeardList(Array)\n#2 /var/www/html/index.php(12): include('/var/www/html/i...')\n#3 {main}\n  thrown in /var/www/html/include/functions.php on line 188
pi@raspi-10:/var/log/apache2 $ 

content of config.php is...
pi@raspi-10:/var/log/apache2 $ cat /var/www/html/config/config.php 
<?php
# This is an auto-generated config-file!
# Be careful, when manual editing this!

date_default_timezone_set('UTC');
define("YSFREFLECTORLOGPATH", "/usr/local/bin");
define("YSFREFLECTORLOGPREFIX", "YSFReflector");
define("YSFREFLECTORINIPATH", "/etc/");
define("YSFREFLECTORINIFILENAME", "YSFReflector.ini");
define("YSFREFLECTORPATH", "/usr/local/bin");
define("TIMEZONE", "Australia/Hobart");
define("LOGO", "Tasmania.gif");
define("REFRESHAFTER", "60");
define("SHOWPROGRESSBARS", "on");
define("SHOWOLDMHEARD", "30");
define("TEMPERATUREALERT", "on");
define("TEMPERATUREHIGHLEVEL", "60");
define("SHOWQRZ", "on");
define("GDPR", "on");
?>
pi@raspi-10:/var/log/apache2 $ 

YSFReflector.ini

`pi@raspi-10:/var/log/apache2 $ cat /etc/YSFReflector.ini 
[General]
Daemon=1

[Info]
# Remember to register your YSFReflector at:
# https://register.ysfreflector.de
Name=AU TAS
Description=BM TG5057

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
FileLevel=1
FilePath=/usr/local/bin
FileRoot=YSFReflector

[Network]
Port=42000
Debug=0
pi@raspi-10:/var/log/apache2 $ 

This worked fine before the most recent edits pushed to github. Am I missing any expected requirements that are not covered in the README.md or linux-step-by-step.md

If I change the logfile path so that the current log isn't getting processed the page displays but without and radio heard data populating it `...

**Comment by dg9vh** [comment]
It may be a problem with the "Show old MHeard"-functionality. Please leave the option in setup.php empty or comment line 65 to 67 out in index.php:

/*if (defined("SHOWOLDMHEARD")) {
  include "include/oldheard.php";
}*/

**Comment by vk7hse** [comment]
Confirmed, if I set that history to 0 (zero) the error is no more! :)
