### ISSUE TITLE
Duplicate entries in last heard and all time last heard

### ISSUE THREAD

**Issue by ke8o** [dg9vh/YSFReflector-Dashboard#17]
After upgrading the dashboard I’m finding duplicate entries in the last head and all time last heard.

https://ysf.glorb.com/

Any suggestion on how to resolve?

**Comment by dg9vh** [comment]
I'll take a look at it.

**Comment by dg9vh** [comment]
This is no issue of the dashboard - this is a known issue of the YSFReflector itself. You could fix it as hotfix by restarting it after 0:00 UTC via cron-job.

73 de Kim
DG9VH
