### ISSUE TITLE
ysf philly dashboard

### ISSUE THREAD

**Issue by manonegra1** [dg9vh/YSFReflector-Dashboard#20]
hi there just got my reflector running but i have a issue with the dashboard not seeing any login any help.

**Comment by manonegra1** [comment]
my reflector us ysf philly

**Comment by dg9vh** [comment]
As I can see on http://ham.daotechnologies.com/ysf-dashboard/ - all is working good.

**Comment by manonegra1** [comment]
kim my dashboard is not working correcly this is not mine  http://ham.daotechnologies.com/ysf-dashboard/ mine is us ysf philly/pasolaysf,71.185.217.74/
    On Tuesday, May 28, 2019, 12:58:10 PM EDT, Kim - DG9VH <notifications@github.com> wrote:  
 
 
Closed #20.

**Comment by manonegra1** [comment]
dashboard looks like is working but when i key or my friend key nothing is showing.   US YSF PHILLY / PASOLA YSF

**Comment by dg9vh** [comment]
Hi, 

I can't find your reflector online and the website is not responding.
Please check reachability from internet side.

73 de Kim
DG9VH

**Comment by manonegra1** [comment]
is not showing up dont know what happend may have to do a fresh image

    On Wednesday, May 29, 2019, 2:02:46 AM EDT, Kim - DG9VH <notifications@github.com> wrote:  
 
 
Hi,

I can't find your reflector online and the website is not responding.
Please check reachability from internet side.

73 de Kim
DG9VH

**Comment by manonegra1** [comment]
is up again but nothing is showing try it now ee if you see something

**Comment by dg9vh** [comment]
Hi, your dashboard seems not to be configured right... please show me your config.php in the /config - folder and tell me, where your YSFReflector.ini-File resides and where the log-files are stored.

**Comment by dg9vh** [comment]
Also your reflector is not replying when trying to connect it... is the process really running? Is there any router or firewall?

**Comment by manonegra1** [comment]
okay let see i'm new to this let me see how can i get that for you.

**Comment by dg9vh** [comment]
what is the output of the command:

ps ax | grep YSFReflector
?

**Comment by manonegra1** [comment]
oot@raspberrypi:/home/pi# ps ax | grep YSFReflector
 2579 pts/0    S+     0:00 nano YSFReflector.ini
 2675 pts/1    S+     0:00 grep YSFReflector

**Comment by dg9vh** [comment]
ok, your reflector is not running. What happens, if you try to start it with 
YSFReflector /path/to/YSFReflector.ini

where /path/to is the path where your YSFReflector.ini is?

**Comment by manonegra1** [comment]
sorry i'm lost

**Comment by manonegra1** [comment]
nano YSFReflector.ini   when i put this nothing is showing

**Comment by manonegra1** [comment]
[General]
Daemon=0

[Info]
# Remember to register your YSFReflector at:
# https://register.ysfreflector.de
Name=US YSF PHILLY
Description=PASOLA YSF

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
FileLevel=1
FilePath=/usr/local/bin/
FileRoot=YSFReflector

[Network]
Port=42000
Debug=0

**Comment by manonegra1** [comment]
looks like is working now.......

**Comment by dg9vh** [comment]
ok

**Comment by manonegra1** [comment]
is working but the dashboard is not

**Comment by dg9vh** [comment]
Is the log really written in /usr/local/bin?

**Comment by manonegra1** [comment]
kim a have it on now is showing me the dashboard page but the only problom is no data passing trew.

**Comment by manonegra1** [comment]
take it look 71.185.217.74/

**Comment by manonegra1** [comment]
FilePath=/usr/local/bin/ ............now what i don't under stand is when you go and confi the dashboard there is a few setting that i have to change  and i notice that there are some all ready there so i copy the same ones becouse not shure what to put there.

**Comment by manonegra1** [comment]
/var/log/ysfreflector
ysfreflector
/etc/
ysfredflector.ini
/usr/local/bin/

**Comment by manonegra1** [comment]
YSFReflector-Configuration
Path to YSFReflector-logfile      -                        /var/log/YSFReflector

Logfile-prefix                                   -                 YSFReflector         

Path to YSFReflector.ini                   -                  /etc/

YSFReflector.ini-filename         -                            YSFReflector.ini

Path to YSFReflector-executable              -            /usr/local/bin/

is this correct on dashboard setup.

**Comment by manonegra1** [comment]
FilePath=/usr/local/bin/

**Comment by manonegra1** [comment]
looks like some where in here i have something mis config .

**Comment by dg9vh** [comment]
looks ok so far... keep checked, that the reflector is reachable from the internet.
