### ISSUE TITLE
help with ysf reflector dashboard 

### ISSUE THREAD

**Issue by manonegra1** [dg9vh/YSFReflector-Dashboard#21]
stop working nothing is showing

**Comment by manonegra1** [comment]
YSFReflector-Dashboard by DG9VH for Reflector: / 
YSFReflector by G4KLX Version:

**Comment by manonegra1** [comment]
reflector is working fine it just the dashboard.

**Comment by dg9vh** [comment]
Was it working before? Error shows like that you moved YSFReflector.ini to different place or something like that...

**Comment by manonegra1** [comment]
was working before i update and it stop

**Comment by dg9vh** [comment]
How did you update? with git pull or something else? Is the config.php still existing?

**Comment by manonegra1** [comment]
just did a reboot i was trying to see if pathfile was correct and when i reboot gone.

**Comment by manonegra1** [comment]
should i unistall apache2 and do the prosecc again

**Comment by manonegra1** [comment]
how do i check config.php

**Comment by dg9vh** [comment]
just go to your webroot where the dasboard is located, there should be within the dashboard-folder a folder named /config and within this should be a config.php
