### ISSUE TITLE
YSFReflector-Dashboard

### ISSUE THREAD

**Issue by manonegra1** [dg9vh/YSFReflector-Dashboard#22]
why my dashboard isn't working I can fig this out help, 71.185.217.74/ us ysf philly

**Comment by manonegra1** [comment]
no data

**Comment by manonegra1** [comment]
FilePath=/usr/local/bin/
FileRoot=YSFReflector

**Comment by manonegra1** [comment]
DisplayLevel=1
FileLevel=1
FilePath=/usr/local/bin/
FileRoot=YSFReflector
[Network]
Port=42000
Debug=0

**Comment by manonegra1** [comment]
YSFReflector-dashboard-Configuration
Path to YSFReflector-logfile -                                                      /var/log/YSFReflector
Logfile-prefix -                                                                            YSFReflector
Path to YSFReflector.ini -                                                             /etc/
YSFReflector.ini-filename -                                                          YSFReflector.ini
Path to YSFReflector-executable -                                              /usr/local/bin/
is this correct on dashboard setup.

**Comment by dg9vh** [comment]
Please show me the contents of your logfile...

73 de Kim

**Comment by manonegra1** [comment]
how can I get them for you .
what do I have to do.

**Comment by dg9vh** [comment]
Just paste the content of your logfile here... if this is to complicated, I do not suggest to install and run a YSFReflector and the dashboard, then basics of knowledge are missing, sorry...

Just copy the content of the logfile into this ticket.

**Comment by manonegra1** [comment]
#!/bin/bash
### BEGIN INIT INFO
#
# Provides:             YSFReflector
# Required-Start:       $all
# Required-Stop:        
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Example startscript YSFReflector

#
### END INIT INFO
## Fill in name of program here.
PROG="YSFReflector"
PROG_PATH="/usr/local/bin/"
PROG_ARGS="/etc/YSFReflector.ini"
PIDFILE="/var/run/YSFReflector.pid"
USER="root"

start() {
      if [ -e $PIDFILE ]; then
          ## Program is running, exit with error.
          echo "Error! $PROG is currently running!" 1>&2
          exit 1
      else
          cd $PROG_PATH
          ./$PROG $PROG_ARGS
          echo "$PROG started"
          touch $PIDFILE
      fi
}

stop() {
      if [ -e $PIDFILE ]; then
          ## Program is running, so stop it
         echo "$PROG is running"
         rm -f $PIDFILE
         killall $PROG
         echo "$PROG stopped"
      else
          ## Program is not running, exit with error.
          echo "Error! $PROG not started!" 1>&2
          exit 1
      fi
}

## Check to see if we are running as root first.
## Found at
## http://www.cyberciti.biz/tips/shell-root-user-check-script.html
if [ "$(id -u)" != "0" ]; then
      echo "This script must be run as root" 1>&2
      exit 1
fi

case "$1" in
      start)
          start
          exit 0
      ;;
      stop)
          stop
          exit 0
      ;;
      reload|restart|force-reload)
          stop
          sleep 5
          start
          exit 0
      ;;
      **)
          echo "Usage: $0 {start|stop|reload}" 1>&2
          exit 1
      ;;
esac
exit 0
### END

**Comment by manonegra1** [comment]
thanks any way I will study this more closely so I can under stand what im doing 73s.

**Comment by dg9vh** [comment]
Sorry, this is not the Logfile... your logfile is, as you wrote above, under /var/log/YSFReflector...
