### ISSUE TITLE
no data in dashboard

### ISSUE THREAD

**Issue by ZL1CTS** [dg9vh/YSFReflector-Dashboard#23]
Hi
Just set up a YSF reflector, had issues when starting it said cant open log file, fixed those permissions and now it opens and reflector runs OK, but no data is shown on dash or in log file except
M: 2019-10-21 21:18:55.103 Starting YSFReflector-20161021
M: 2019-10-21 21:20:55.265 No repeaters/gateways linked
M: 2019-10-21 21:22:09.101 Starting YSFReflector-20161021
M: 2019-10-21 21:24:23.128 No repeaters/gateways linked
M: 2019-10-21 21:26:23.297 No repeaters/gateways linked
M: 2019-10-21 21:28:23.451 No repeaters/gateways linked
M: 2019-10-21 21:30:23.630 No repeaters/gateways linked
M: 2019-10-21 21:32:23.797 No repeaters/gateways linked

I link to it in pi-star and all works normally, but nothing listed in the log or displayed in the dashboard.. 
I guess I missed something, but cant pinpoint what it is

thanks

Cliff

**Comment by dg9vh** [comment]
The dash only shows, what is written in the log. If there is nothing in the log, check your reflector installation first.

No issue of dashboard. 

73 de Kim
