### ISSUE TITLE
no ID on YSFReflector website

### ISSUE THREAD

**Issue by DU8BL** [dg9vh/YSFReflector-Dashboard#24]
YSFReflector running and working properly. no issues on firewall and can connect using modified YSFClients.txt with dummy room ID via YSF GW. Problem is it is not showing up on the YSFReflector website due to no room ID assigned and when clicking the ping icon i get a blank page. Not sure if this is the place for this concern.

Reflector Name: DX8ZC

**Comment by dg9vh** [comment]
A) this is no dashboard issue
B) you did not click the activation link in the registration email.

**Comment by DU8BL** [comment]
Sorry, posted this issue on the wrong section of YSFRflector. i did not see that this was the dashboard section. sorry.
