### ISSUE TITLE
Date/Time issue

### ISSUE THREAD

**Issue by w4edp** [dg9vh/YSFReflector-Dashboard#25]
Seeing the following on a new Debian 10 installation with PHP7.3.  Any suggestions?

PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string () at position 3 (R): The timezone could not be found in the database in /var/www/YSFDash/include/functions.php:188\nStack trace:\n#0 /var/www/YSFDash/include/functions.php(188): DateTime->__construct('\\x00\\x00\\x00Received dat...')\n#1 /var/www/YSFDash/include/init.php(20): getHeardList(Array)\n#2 /var/www/YSFDash/index.php(12): include('/var/www/YSFDas...')\n#3 {main}\n  thrown in /var/www/YSFDash/include/functions.php on line 188, referer: http://45.32.214.224/YSFDash/setup.php?cmd=writeconfig&YSFREFLECTORLOGPATH=%2Fopt%2FYSFReflector%2F&YSFREFLECTORLOGPREFIX=YSFReflector&YSFREFLECTORINIPATH=%2Fopt%2FYSFReflector%2F&YSFREFLECTORINIFILENAME=YSFReflector.ini&YSFREFLECTORPATH=%2Fopt%2FYSFReflector%2F&TIMEZONE=America%2FNew_York&LOGO=&REFRESHAFTER=60&SHOWPROGRESSBARS=on&SHOWOLDMHEARD=10&TEMPERATUREHIGHLEVEL=80&SHOWQRZ=on

**Comment by w4edp** [comment]
The issue looks like it's here, line 188 of functions.php, that is not getting set
but I do not know where to go from there...

$dttimestamp = new DateTime($timestamp);

**Comment by dg9vh** [comment]
What loglevels do you have in your MMDVM.ini for file-logging?

**Comment by w4edp** [comment]
This is for YSFReflector, also this is working on a Debian 9 box with PHP 7.0

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
FileLevel=1
FilePath=/opt/YSFReflector
FileRoot=YSFReflector

**Comment by w4edp** [comment]
In the below function, $timestamp produces output if echo'ed, but $dttimestamp gives nothing.

function getHeardList($logLines) {
        $heardList = array();
        $dttxend = "";
        foreach ($logLines as $logLine) {
                $duration = "transmitting";
                $timestamp = substr($logLine, 3, 19);
                $dttimestamp = new DateTime($timestamp);

**Comment by dg9vh** [comment]
has it been working on any time?

**Comment by w4edp** [comment]
> has it been working on any time?

Not on Debian 10 and PHP7.3.  It does work on Debian 9 and PHP 7.0.

**Comment by dg9vh** [comment]
Have you checked timezone-configuration on the linux-system? Did you try it out with a log working on your Debian 9-system? Just to find the source of this error...

**Comment by w4edp** [comment]
> Have you checked timezone-configuration on the linux-system? Did you try it out with a log working on your Debian 9-system? Just to find the source of this error...

Time zone info is correct as far as I can tell on the Debian 10 server.  I have looked  at things like timedatectl  on both servers and they are the same.

 sudo timedatectl
      Local time: Fri 2020-04-03 14:56:02 EDT
  Universal time: Fri 2020-04-03 18:56:02 UTC
        RTC time: Fri 2020-04-03 18:56:02
       Time zone: America/New_York (EDT, -0400)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no

**Comment by w4edp** [comment]
This does not seem to work or produce any output on the Debian 10 PHP 7.3 server:

$dttimestamp = new DateTime($timestamp);

**Comment by dg9vh** [comment]
So it would be worth to copy the working logfile to the log-location on your current system to give an idea, if it is something produced within the log-file or if it is something on some behavior of your environment.

**Comment by dg9vh** [comment]
What's the content of $timestamp?

**Comment by w4edp** [comment]
I tried that, the log from the Debian 9/PHP7.0 server that works does not work on the Debian 10/PHP7.3 server

**Comment by dg9vh** [comment]
so ok, no issue with the logfile-format itself...

**Comment by w4edp** [comment]
If I do this:
function getHeardList($logLines) {
        $heardList = array();
        $dttxend = "";
        foreach ($logLines as $logLine) {
                $duration = "transmitting";
                $timestamp = substr($logLine, 3, 19);
**echo $timestamp;**
                $dttimestamp = new DateTime($timestamp);

I get this:

2020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:022020-03-25 17:43:02Received data fr
Fatal error: Uncaught Exception: DateTime::__construct(): Failed to parse time string () at position 3 (R): The timezone could not be found in the database in /var/www/YSFDash/include/functions.php:189 Stack trace: #0 /var/www/YSFDash/include/functions.php(189): DateTime->__construct('\x00\x00\x00Received dat...') #1 /var/www/YSFDash/include/init.php(20): getHeardList(Array) #2 /var/www/YSFDash/index.php(12): include('/var/www/YSFDas...') #3 {main} thrown in /var/www/YSFDash/include/functions.php on line 189

**Comment by w4edp** [comment]
If I do this:

function getHeardList($logLines) {
        $heardList = array();
        $dttxend = "";
        foreach ($logLines as $logLine) {
                $duration = "transmitting";
                $timestamp = substr($logLine, 3, 19);
**echo $timestamp;**
                $dttimestamp = new DateTime($timestamp);
**echo $dttimestamp;**
                if ($dttxend !== "") {
                        $duration = $dttimestamp->diff($dttxend)->format("%s");
                }

I get:

2020-04-03 00:04:55
Recoverable fatal error: Object of class DateTime could not be converted to string in /var/www/YSFDash/include/functions.php on line 190

**Comment by dg9vh** [comment]
Well, I think for getting $dttimestamp you should use var_dump(...) - function...

But more of interest would be the content of $logLine - so please put an 
echo $logLine before your
echo $timestamp line... 

I think there would be a string at the position, the DateTime-creator would be f.cked up :-)

**Comment by dg9vh** [comment]
for better reading you could add `."<br>\n"` behind the variable-names
so 
`echo $logLine ."<br>\n";`
and
`echo $timestamp."<br>\n";`

**Comment by w4edp** [comment]
> for better reading you could add `."<br>\n"` behind the variable-names
> so
> `echo $logLine ."<br>\n";`
> and
> `echo $timestamp."<br>\n";`

I added

 function getHeardList($logLines) {
        $heardList = array();
        $dttxend = "";
        foreach ($logLines as $logLine) {
                $duration = "transmitting";
                $timestamp = substr($logLine, 3, 19);
**echo $logLine ."<br>\n";
echo $timestamp ."<br>\n";**
                $dttimestamp = new DateTime($timestamp);

as suggested and you can see output here: http://45.32.214.224/YSFDash/index.php

**Comment by w4edp** [comment]
I do appreciate all your help and will be glad to donate to the cause if you have a PayPal address.  This is the only thing holding me up from moving things to a new server.

**Comment by dg9vh** [comment]
Well, there is this line a bit crazy:
Received data from %10.10s to %10.10s at %10.10sRemoving %s (%s:%u) disappearedUsage: YSFReflector [-v|--version] [filename]

This line has nothing to do with regular logging information of YSFReflector... that makes me wondering now...

Please be so kind and email me your logfile to have a look at it... dg9vh@dg9vh.de

**Comment by dg9vh** [comment]
For Paypal-donations you can use the button at the bottom of https://register.ysfreflector.de/

**Comment by w4edp** [comment]
> Well, there is this line a bit crazy:
> Received data from %10.10s to %10.10s at %10.10sRemoving %s (%s:%u) disappearedUsage: YSFReflector [-v|--version] [filename]
> 
> This line has nothing to do with regular logging information of YSFReflector... that makes me wondering now...
> 
> Please be so kind and email me your logfile to have a look at it... [dg9vh@dg9vh.de](mailto:dg9vh@dg9vh.de)

On it's way!

**Comment by w4edp** [comment]
> For Paypal-donations you can use the button at the bottom of https://register.ysfreflector.de/

Done!

**Comment by dg9vh** [comment]
> > For Paypal-donations you can use the button at the bottom of https://register.ysfreflector.de/
> 
> Done!

Thanks :-) you are crazy...

**Comment by w4edp** [comment]
> > > For Paypal-donations you can use the button at the bottom of https://register.ysfreflector.de/
> > 
> > 
> > Done!
> 
> Thanks :-) you are crazy...

Not the 1st to tell me that!  I use many of the Dashboards and I appreciate the time you guys put in to them.  I wish I had your coding skills...

**Comment by dg9vh** [comment]
Just setting up a debugging-environment on a raspberry pi to find the problem... your log runs on my systems with php7.1 like a cat... but i will find the problem :-)

**Comment by w4edp** [comment]
> Just setting up a debugging-environment on a raspberry pi to find the problem... your log runs on my systems with php7.1 like a cat... but i will find the problem :-)

Thank You!

**Comment by dg9vh** [comment]
Could you please post your YSFReflector.ini?

**Comment by w4edp** [comment]
> Could you please post your YSFReflector.ini?

[General]
Daemon=1

[Info]
# Remember to register your YSFReflector at:
# https://register.ysfreflector.de
Name=US SOUTHEASTLINK
Description=lmarc.net

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
FileLevel=1
FilePath=/opt/YSFReflector
FileRoot=YSFReflector

[Network]
Port=42000
Debug=0

**Comment by dg9vh** [comment]
Looks good so far but it now could be a file permission problem with reading-permissions for the apache-webservice-user to /opt/YSFReflector...

just try following:
sudo chmod -R og+r /opt/
This would give all users on your system read-permissions on the /opt-directory and below, so the webserver should find the logfile...

**Comment by dg9vh** [comment]
No! I got the solution:
It is a problem with the location itself!
Because we grab some old logfiles all files beginning with YSFReflector would be grabbed and because of you have your binary also in /opt/YSFReflector, this would be no good :-)

So do following:
change FilePath to 
FilePath=/var/log/YSFReflector

then create a log-directory:
sudo mkdir /var/log/YSFReflector
and change owner to mmdvm:
chown mmdvm /var/log/YSFReflector
then make it readable for all:
sudo chmod -R og+r /var/log/YSFReflector
and finally restart the reflector

**Comment by w4edp** [comment]
OK, will do that and let you know soon.  Thanks!

**Comment by dg9vh** [comment]
This should be the source of the error... I now reconstructed it on my server like your installation and voila, got following in my error.log:
[Fri Apr 03 20:46:41.516374 2020] [:error] [pid 19818] [client 188.107.142.48:60170] PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string () at position 3 (R): The timezone could not be found in the database in /var/www/c4fm.ysfreflector.de/dev/include/functions.php:188\nStack trace:\n#0 /var/www/c4fm.ysfreflector.de/dev/include/functions.php(188): DateTime->__construct('\\x00\\x00\\x00Received dat...')\n#1 /var/www/c4fm.ysfreflector.de/dev/include/init.php(20): getHeardList(Array)\n#2 /var/www/c4fm.ysfreflector.de/dev/index.php(12): include('/var/www/c4fm.y...')\n#3 {main}\n  thrown in /var/www/c4fm.ysfreflector.de/dev/include/functions.php on line 188
[Fri Apr 03 20:46:44.136676 2020] [:error] [pid 19821] [client 188.107.142.48:60172] PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string () at position 3 (R): The timezone could not be found in the database in /var/www/c4fm.ysfreflector.de/dev/include/functions.php:188\nStack trace:\n#0 /var/www/c4fm.ysfreflector.de/dev/include/functions.php(188): DateTime->__construct('\\x00\\x00\\x00Received dat...')\n#1 /var/www/c4fm.ysfreflector.de/dev/include/init.php(20): getHeardList(Array)\n#2 /var/www/c4fm.ysfreflector.de/dev/index.php(12): include('/var/www/c4fm.y...')\n#3 {main}\n  thrown in /var/www/c4fm.ysfreflector.de/dev/include/functions.php on line 188

**Comment by dg9vh** [comment]
looks very similar to your error - so this would be the solution: moving the logfiles to a different directoy like suggested above...

**Comment by dg9vh** [comment]
Keep in mind to change the log-directory in your config/config.php to the new location :-)

**Comment by dg9vh** [comment]
means:
`define("YSFREFLECTORLOGPATH", "/var/log/YSFReflector/");`

**Comment by dg9vh** [comment]
now you should tune your php.ini a bit to get this nasty things away:
Notice: A non well formed numeric value encountered in /var/www/YSFDash/include/sysinfo.php on line 96

Notice: A non well formed numeric value encountered in /var/www/YSFDash/include/sysinfo.php on line 96

just look for 
error_reporting and set it to:
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

**Comment by w4edp** [comment]
It's working, but I see this

Notice: Undefined offset: 14296 in /var/www/YSFDash/include/functions.php on line 153
Notice: Undefined offset: 14296 in /var/www/YSFDash/include/functions.php on line 163

You can se it at http://45.32.214.224/YSFDash/index.php

**Comment by dg9vh** [comment]
just make the suggested change above:
just look for
error_reporting in your php.ini and set it to:
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
and restart your webserver (sudo service apache2 restart)

**Comment by w4edp** [comment]
That got rid of all but one:

Warning: Use of undefined constant DISTRIBUTION - assumed 'DISTRIBUTION' (this will throw an Error in a future version of PHP) in /var/www/YSFDash/include/tools.php on line 69

**Comment by w4edp** [comment]
Got it!  Just replace DISTRIBUTION with 'DISTRIBUTION' in include/tools.php on line 69

**Comment by dg9vh** [comment]
ok... tnx for the hint... would track it then... so tnx for your donation :-) It would be used to sponsor my son's activities :-) as you can imagine, kids at age of 9 yrs have expensive ideas :-) You would give me the possibility to make some of them get real, hi :-) So have a nice evening!

**Comment by w4edp** [comment]
> ok... tnx for the hint... would track it then... so tnx for your donation :-) It would be used to sponsor my son's activities :-) as you can imagine, kids at age of 9 yrs have expensive ideas :-) You would give me the possibility to make some of them get real, hi :-) So have a nice evening!

Awesome!  Thanks for the help!
