### ISSUE TITLE
YSFReflector-Dashboard BlockList

### ISSUE THREAD

**Issue by r3pij** [dg9vh/YSFReflector-Dashboard#30]
Dashboard does not correctly display callsign blocking in ysfreflector
![SmartSelect_20210227-175527_Gallery](https://user-images.githubusercontent.com/79754522/109390851-0c2da180-7925-11eb-9ba9-ba38c8829c4f.jpg)
![SmartSelect_20210227-175455_Gallery](https://user-images.githubusercontent.com/79754522/109390852-0d5ece80-7925-11eb-9e05-9ac7c5d69889.jpg)

**Comment by dg9vh** [comment]
What kind of way do you think would be the best to handle this? Ignoring this lines (would be the easiest way I think) and with this don't get aggression of blocked people or showing the fact that this transmission was blocked?

I am unsure how to handle this... in the new version of the dashboard the transmissions will be ignored as I remember... so I tend to do it similar here.

**Comment by dg9vh** [comment]
Commited version that's ignoring this... please test it... I have actually no test-environment for this.

**Comment by r3pij** [comment]
Do not ignore if possible.  The logfile contains several lines of one blocked transfer.  Will this cause additional problems?

**Comment by r3pij** [comment]
> Commited version that's ignoring this... please test it... I have actually no test-environment for this.

Yes.  Now this is ignored.

**Comment by dg9vh** [comment]
I think showing callsigns to be ignored/blocked opens the field for much discussions, so I do not show the lines... It would also produce some complicated things to make this infos "unique" to be shown on the board... 

I think now we can live with it :-)
