### ISSUE TITLE
YSFV command

### ISSUE THREAD

**Issue by is0gqx** [dg9vh/YSFReflector-Dashboard#31]
Hi Kim,
Please consider the change to prevent periodic Reflector Activity Monitor messages from being displayed.
In particular, in the absence of traffic, they fill the dashboard and it becomes unwelcome to see.
I am using your latest dashboard and have been testing with the latest version of pYSFReflector by IU5JAE.

![YSFV command](https://user-images.githubusercontent.com/70938906/113106167-ba698700-9202-11eb-9610-31e31b8486e5.png)

Many thanks for your eventual time spent on this.
73, Bruno IS0GQX

**Comment by dg9vh** [comment]
Ok, thought I had modified the code already. Will check. Tnx Fer info.

**Comment by is0gqx** [comment]
thanks again Kim,
I forgot, when FileRotate = 0 in YSFReflector.ini the dashboard does not read the file YSFReflector.log (without end date).

73, Bruno IS0GQX

**Comment by dg9vh** [comment]
The php-version of the dashboard does not support filerotate = 0... IF you want to use this, you have to use the new dashboard at https://github.com/dg9vh/WSYSFDash

73 de Kim
DG9VH

**Comment by is0gqx** [comment]
thank you so much ... now all OK.
Good for the new dashboard and congratulations on the great job.

73, Bruno IS0GQX

**Comment by dg9vh** [comment]
tu vy :-)
