### ISSUE TITLE
YSF blocking.

### ISSUE THREAD

**Issue by LiamLewis2011** [dg9vh/YSFReflector-Dashboard#33]
Just wondering how can I block certain callsign from accessing a reflector if for example they are disruptive, cause qrm or are generally a nuisance ?? 

How is this done

**Comment by dg9vh** [comment]
This is a feature of the used YSFReflector - please contact the
corresponding developer of the Reflector you are using.

**Comment by LiamLewis2011** [comment]
😁 I am the owner of the reflector just unsure how to block callsigns from accessing 


Sent from Yahoo Mail for iPhone


On Thursday, February 24, 2022, 11:19 am, Kim - DG9VH ***@***.***> wrote:



This is a feature of the used YSFReflector - please contact the
corresponding developer of the Reflector you are using.

**Comment by dg9vh** [comment]
I know, but you did not develop it, you downloaded it from github or
somewhere so contact the person who programmed the code you are using!
