### ISSUE TITLE
Currently TXing not working....

### ISSUE THREAD

**Issue by jsuede326** [dg9vh/YSFReflector-Dashboard#35]
do not see any call signs appear in the "Currently TXing " portion of the Dashboard.  Everything appears to be working, people can communicate over the reflector and I see no errors in the log files;  just do not see any call signs appear in the "Currently TXing " portion of the Dashboard.  This was all working perfectly fine in the older versions of code from Jun 2022.

I just upgraded the Reflector code to the latest ( Jan 15 2023 code of Reflector by G4KLX Version 20210824 ) and have reinstalled to the latest version of the Dashboard code as well....

**Comment by dg9vh** [comment]
This is the old Dashboard that is no longer in development.

If someone catches the cause and pulls a patch, I will merge it.

73
