### ISSUE TITLE
My YSF Reflector is showing registered off-line.

### ISSUE THREAD

**Issue by TimBastress** [dg9vh/YSFReflector-Dashboard#36]
So I have installed the QSO365 YSF Reflector and installed the DG9VH YSFReflector Dashboard.    I registered my YSFReflector and it has been showing offline for almost a day now.   I had to add a port forwarding rule in my router to get access to the dash board and that is now working great!    So I also added a port forwarding rule for port 42000 but that hasn't made any difference and my YSF is still offline.  How can I trouble shoot this issue?  Everything seemed to install smoothly, but no dice.  Any help you can offer would be greatly appreciated.   By the way my YSF Reflector is #45150 and the dashboard is at w8mrc.net

**Comment by dg9vh** [comment]
First: This is not a Dashboard related problem.
Second: It is listed online, as you can see on register.ysfreflector.de - where is it listed offline? Please contact the persons providing the data for your system.

73 de Kim
DG9VH

**Comment by TimBastress** [comment]
If you'll look on register.ysfreflector.de it shows as offline.   Thank you for answering me.  Unfortunately I'm not a Linux man so I'm in the dark on how to fix my issue.  The installation of the YSF reflector from QSO365 seemed to go smoothly as far as I could see.  And your dashboard install went smoothly as well.   Your product seems to be working but I can't seem to get the reflector to report in.    Can you tell me how the ysfreflector.de site determines if a ysf reflector is active or not?  Is it looking for a handshake of some sort to come from the ysf reflector or does it send a query to my reflector and my reflector isnt responding?  Are there any files that I could send you to help me resolve the issue?  Again any help is greatly appreciated.

**Comment by dg9vh** [comment]
Ah, sorry, I was looking up for qso365 ... Keeper secure udp traffic is forwarded and hostname is mapping correct IP address

**Comment by TimBastress** [comment]
I believe the hostname is mapping correctly since the web page is
responding properly.
What is a good way to test externally if the udp port 42000 is reaching
into the PI as well?

**Comment by dg9vh** [comment]
take a look at the router configuration of port forwards... 42000 must be directed to the internal ip-address of your pi.

**Comment by TimBastress** [comment]
Hi Kim,
After doing much tracing of the install file it appears that G4KLX has
taken down the YSFReflector files from his github site.  So the install.sh
file that references that site is pulling a bunch of nothing.    I don't
know why he has done that but they are indeed missing.   I'm of course very
frustrated as I have spent a lot of time of my own, plus yours and several
others just to find out the files have been taken down and are missing.
 Im sorry to have wasted your time.  Please let others know this problem if
anyone else reaches out to you about the G4KLX YSF Reflector.

So that being said, do you know if any other good YSF Reflector builds out
there on the internet?  Will your dashboard work with any other YSF
Reflectors?


Tim

**Comment by TimBastress** [comment]
Well I found another one but n5amd also ends up referring back to the G4KLX
YSFReflector files that dont exist anymore.  Other than that his install
files are smooth as silk.

Do you happen to have a copy of the original YSFRelector files from G4KLX?
 I sure could use them about now.

**Comment by dg9vh** [comment]
You can give pYSFReflector a go. Otherwise, the Code was taken over by some guys, but I actually have no info to who its maintaining now.

**Comment by TimBastress** [comment]
What do you know about the XLX reflectors? Will they show up on your
reflector list as well?

**Comment by dg9vh** [comment]
Yes, they will
