### ISSUE TITLE
setup.php rendering a broken page

### ISSUE THREAD

**Issue by eriktheswede** [dg9vh/YSFReflector-Dashboard#39]
When accessing setup.php after following the instructions, a broken page is loaded.

Fresh Debian 12 install running Apache 2 and PHP 8.2. PHP is confirmed working.

The website source stops loading after line 45. Tested in the most current versions of Chrome and Safari.

![Screenshot 2023-11-03 at 00 37 07](https://github.com/dg9vh/YSFReflector-Dashboard/assets/35968789/0d1d9898-2e78-4ba6-a5fc-ba36d23e1b50)

**Comment by dg9vh** [comment]
The dashboard is no longer under development and support.
