### ISSUE TITLE
Clarification Of Step "Create a group for the webserver and add yourself to it"

### ISSUE THREAD

**Issue by VortexFL** [dg9vh/YSFReflector-Dashboard#4]
I am working on the 2nd part of my YSFReflector setup.  Here is error I get "You forgot to give write-permissions to your webserver-user!".

https://github.com/dg9vh/YSFReflector-Dashboard/blob/master/linux-step-by-step.md

I know I missed something just not sure. I signed and went to root to make the changes.

Text from Page: 
Create a group for the webserver and add yourself to it:
sudo groupadd www-data
sudo usermod -G www-data -a

My web server is using www-data.

total 52
-rwxrwxr-x 1 www-data www-data 9154 Feb 27 20:25 setup.php
drwxrwxr-x 3 www-data www-data 4096 Feb 27 14:32 .
-rwxrwxr-x 1 www-data www-data   41 Feb 27 14:31 version.php
drwxrwxr-x 2 www-data www-data 4096 Feb 27 14:31 include
-rwxrwxr-x 1 www-data www-data 3351 Feb 27 14:31 index.php
-rwxrwxr-x 1 www-data www-data 6555 Feb 27 14:31 LICENSE
-rwxrwxr-x 1 www-data www-data 2093 Feb 27 14:31 linux-step-by-step.md
-rwxrwxr-x 1 www-data www-data  961 Feb 27 14:31 README.md
-rwxrwxr-x 1 www-data www-data 1149 Feb 27 14:31 txinfo.php
drwxr-xr-x 3 root     root     4096 Feb 27 14:30 ..

**Comment by dg9vh** [comment]
@VortexFL Hi,
just create a directory "config" within the dashboard-directory and give write-permissions to www-data

**Comment by kikosgc** [comment]
Still don't get it...

**Comment by xe1dvi** [comment]
Im having the same issue, created sub directory in Dash as mentioned above but still wont work.
Please advise.

**Comment by dg9vh** [comment]
Is this still actual or is it resolved by installing php? If still an issue, reopen and give more information like URL to test or something like logfiles from webserver etc.

**Comment by xe1dvi** [comment]
You can close it now. I figured out, my DashBoard is up and running.

**Comment by dg9vh** [comment]
ok, tnx
