### ISSUE TITLE
Dashboard dont show the data

### ISSUE THREAD

**Issue by lu9cbl** [dg9vh/YSFReflector-Dashboard#6]
Hi! i'm installing the dashboard as always, but this time don't show me the data (http://ysfargentina.dnsalias.com/). Can i'm search in any log inside the dashboard to see what's happening???

Thanks!
Mati LU9CBL

**Comment by dg9vh** [comment]
You can take a look into the Webserver error log. Would you show us your config.php? -- Amateurfunk ist das, was uns verbindet! Bleiben wir in Kontakt! Ortsverband Q05, VölklingenAm 18.03.2018 00:21 schrieb "Mat (LU9CBL)" <notifications@github.com>:Hi! i'm installing the dashboard as always, but this time don't show me the data (http://ysfargentina.dnsalias.com/). Can i'm search in any log inside the dashboard to see what's happening???
Thanks!
Mati LU9CBL

**Comment by lu9cbl** [comment]
i'm will search the logs in the webserver. The config file:

<?php
# This is an auto-generated config-file!
# Be careful, when manual editing this!

date_default_timezone_set('UTC');
define("YSFREFLECTORLOGPATH", "/var/log/YSFReflector");
define("YSFREFLECTORLOGPREFIX", "ARGENTINA LINK");
define("YSFREFLECTORINIPATH", "/etc/");
define("YSFREFLECTORINIFILENAME", "YSFReflector.ini");
define("YSFREFLECTORPATH", "/usr/local/bin/");
define("TIMEZONE", "America/Argentina/Buenos_Aires");
define("LOGO", "https://ugc.kn3.net/i/origin/http://www.ecolo.mrecic.gov.ar/userfiles/BANDERA_ARGENTINA.png");
define("REFRESHAFTER", "60");
define("SHOWPROGRESSBARS", "on");
define("TEMPERATUREALERT", "on");
define("TEMPERATUREHIGHLEVEL", "60");
define("SHOWQRZ", "on");
?>

**Comment by lu9cbl** [comment]
i'm will search the logs in the webserver. The config file:

```
<?php
# This is an auto-generated config-file!
# Be careful, when manual editing this!

date_default_timezone_set('UTC');
define("YSFREFLECTORLOGPATH", "/var/log/YSFReflector");
define("YSFREFLECTORLOGPREFIX", "ARGENTINA LINK");
define("YSFREFLECTORINIPATH", "/etc/");
define("YSFREFLECTORINIFILENAME", "YSFReflector.ini");
define("YSFREFLECTORPATH", "/usr/local/bin/");
define("TIMEZONE", "America/Argentina/Buenos_Aires");
define("LOGO", "https://ugc.kn3.net/i/origin/http://www.ecolo.mrecic.gov.ar/userfiles/BANDERA_ARGENTINA.png");
define("REFRESHAFTER", "60");
define("SHOWPROGRESSBARS", "on");
define("TEMPERATUREALERT", "on");
define("TEMPERATUREHIGHLEVEL", "60");
define("SHOWQRZ", "on");
?>

```

**Comment by dg9vh** [comment]
Hi, I do not think that the logfile is named ARGENTINA LINK-2018-03-18.log, right?
You have to put in here the content of the FileRoot= Parameter in the YSFReflector.ini.

**Comment by lu8eut** [comment]
YSFReflector-2018-03-15.log, log file in /usr/local/bin
YSFReflector.ini
[General]
Daemon=1

[Info]
# Remember to register your YSFReflector at:
# https://register.ysfreflector.de
Name=ARGENTINA LINK
Description=Link to TG7227

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
FileLevel=1
FilePath=/usr/local/bin/
FileRoot=YSFReflector

[Network]
Port=42000
Debug=0
Thanks
R

**Comment by dg9vh** [comment]
Please edit the following line in your config:

define("YSFREFLECTORLOGPREFIX", "ARGENTINA LINK");
to

define("YSFREFLECTORLOGPREFIX", "YSFReflector");
