### ISSUE TITLE
CA NKA-Aerospace can't get online

### ISSUE THREAD

**Issue by VE2TIH** [dg9vh/YSFReflector-Dashboard#7]
Hi, here VE2TIH
I must have done a type during registering: VE2YIH is not my callsign, please correct it to VE2TIH if possible...
Thanks DG9VH !
73
Mike

**Comment by VE2TIH** [comment]
Ho I forgot, I can see polling is from 213.202.229.15... Is that the only IP that will be used (because I GeoIpFiltering activated but I white listed 213.202.229.15) ?
Mike

**Comment by dg9vh** [comment]
Hi, Yes, this is the only host polling.

73 de Kim
DG9VH

**Comment by VE2TIH** [comment]
ok good, do you think that the wrong callsing have something to do with the fact that it's not coming online  or it's something else ?

**Comment by dg9vh** [comment]
Hi, you registered it with 

thibodude.com | 47560
hostname | Port

is that also configured in YSFReflector.ini as port and is the firewall accepting udp-traffic from every port to this port? the outgoing port from polling service is random...

**Comment by VE2TIH** [comment]
Here's the content of the ini file:

[General]
Daemon=1

[Info]
# Remember to register your YSFReflector at:
# https://register.ysfreflector.de
Name=CA NKA-Aerospace
Description=Team chat room

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
FileLevel=1
FilePath=.
FileRoot=YSFReflector

[Network]
Port=47560
Debug=0

Ports forwarding is open on UDP 47560 and TCP 47560 and HTTP (80) also.

Mike VE2TIH

------ Original Message ------

**Comment by dg9vh** [comment]
please check, if the process is running with

ps aux |grep YSFReflector

You should get two lines as result... one with the process of YSFReflector and one with your grep-line

**Comment by VE2TIH** [comment]
I only have one
michel@thibundo:~$ ps aux|grep YSFReflector
michel   22555  0.0  0.0  14352  1076 pts/0    S+   18:08   0:00 grep --color=auto YSFReflector

**Comment by VE2TIH** [comment]
This is now corrected, I think:
michel@thibundo:~$ ps aux |grep YSFReflector
mmdvm     7706  0.8  0.1  24276  2152 ?        Ss   20:01   0:26 /usr/local/bin/YSFReflector /etc/YSFReflector.ini
michel   15053  0.0  0.0  14352  1096 pts/0    S+   20:54   0:00 grep --color=auto YSFReflector

**Comment by VE2TIH** [comment]
But https://register.ysfreflector.de/ is still showing us DOWN (NKA-Abitibi). What is the polling interval ?

**Comment by dg9vh** [comment]
Is host addresses thibodude.com correct?

**Comment by VE2TIH** [comment]
yes, thibodude.com is pointing to 24.212.47.50, this is my domain:

C:\Users\Michel>nslookup
Default Server:  raspberrypi
Address:  10.250.0.11

 > name thibodude.com
Server:  thibodude.com
Address:  24.212.47.50

 > name nka.thibodude.com
Server:  nka.thibodude.com
Address:  24.212.47.50

___________________________________________
Here's my ini file

  cat /etc/YSFReflector.ini

[General]
Daemon=1

[Info]
# Remember to register your YSFReflector at:
# https://register.ysfreflector.de
Name=CA NKA-Aerospace
Description=Team chat room
FilePath=/usr/local/bin/
FileRoot=YSFReflector
[Log]
# Logging levels, 0=No logging
DisplayLevel=0
FileLevel=0
FilePath=.
FileRoot=YSFReflector

[Network]
Port=47560
Debug=0
------------------------------------------------------------
  ps -aux|grep YSFR
mmdvm     7706  0.7  0.1  24276  2152 ?        Ss   Jun06   4:33 
/usr/local/bin/YSFReflector /etc/YSFReflector.ini
michel   24274  0.0  0.0  14352  1132 pts/0    S+   06:12   0:00 grep 
--color=auto YSFR
________________________________________
Mike VE2TIH

------ Original Message ------

**Comment by dg9vh** [comment]
I see this reflector still offline... did you check your firewall settings?

**Comment by dg9vh** [comment]
If this issue still persists and we can help, reopen
