### ISSUE TITLE
No dashboard data

### ISSUE THREAD

**Issue by sixfootseven** [dg9vh/YSFReflector-Dashboard#9]
Try as I might, i cant get the dashboard to show any connections.

Installed reflector and its running and registered and I can connect to it. However, the dashboard never shows a connection.

I installed the dashboard software from here, set the mmdvm user up, mmdvm is in the www-data group, and also has read/write permission for the logfile - but the log file never gets written to.

Ive specified /var/log and YSFReflector

Any ideas? Im relatively experienced in Linux, we run an XLX with transcoding, and lots of custom work, but i cant get this lovely dashboard working :(

**Comment by dg9vh** [comment]
could you post your config.php here? please check, if the webserver-user has read-access to the logdirectory.

**Comment by sixfootseven** [comment]
Thanks for a very quick reply...


`<?php
# This is an auto-generated config-file!
# Be careful, when manual editing this!

date_default_timezone_set('UTC');
define("YSFREFLECTORLOGPATH", "/var/log/");
define("YSFREFLECTORLOGPREFIX", "YSFReflector");
define("YSFREFLECTORINIPATH", "/etc/");
define("YSFREFLECTORINIFILENAME", "YSFReflector.ini");
define("YSFREFLECTORPATH", "/usr/local/bin");
define("TIMEZONE", "Pacific/Auckland");
define("LOGO", "");
define("REFRESHAFTER", "60");
define("SHOWPROGRESSBARS", "on");
define("TEMPERATUREALERT", "on");
define("TEMPERATUREHIGHLEVEL", "60");
define("SHOWQRZ", "on");
?>
`

**Comment by sixfootseven** [comment]
I created a file called /var/log/YSFReflector and the webserver user can read/write to it.

**Comment by dg9vh** [comment]
so is the logfile filled with logdata by the reflector itself? May you configured the reflector wrong with the logpath? YSFReflector.ini please :-)

**Comment by sixfootseven** [comment]
`[General]
Daemon=1

[Info]
# Remember to register your YSFReflector at:
# https://register.ysfreflector.de
Name=NZ XLX626
Description=NZ Official

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
FileLevel=1
FilePath=.
FileRoot=YSFReflector

[Network]
Port=42000
Debug=0`

**Comment by sixfootseven** [comment]
Absolutely nothing in the logfile :(

**Comment by dg9vh** [comment]
That's it:
set 
FilePath=/var/log/
and I think it would be running... keep sure, that mmdvm-user could create logfiles within your logdirectory

**Comment by dg9vh** [comment]
Otherwise you get trouble after 0:00 UTC, when logrotation follows and mmdvm-user has no possibility to create the log

**Comment by sixfootseven** [comment]
Wonderful help thankyou. All working now - I appreciate the effort. :)

**Comment by dg9vh** [comment]
thank you for feedback :-) 73
